apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-docs-pvc
  namespace: bridgex
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi