---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: bridgex
  name: backend-secret-vault
spec:
  provider: vault
  parameters:
    roleName: 'k8s'
    vaultAddress: 'https://192.168.1.150:8200'
    vaultSkipTLSVerify: "true"
    ## I have mounted this at the daemonSet of the vault CSI provided 
    vaultCACertPath: "/etc/vault-tls/ca.crt"
    objects: |
      - objectName: "ALGORITHM"
        secretPath: "bridgex/data/backend"
        secretKey: "ALGORITHM"

      - objectName: "DBCONNECTIONSTRING"
        secretPath: "bridgex/data/backend"
        secretKey: "DBCONNECTIONSTRING"

      - objectName: "EMAILPASS"
        secretPath: "bridgex/data/backend"
        secretKey: "EMAILPASS"

      - objectName: "EMAILUSER"
        secretPath: "bridgex/data/backend"
        secretKey: "EMAILUSER"

      - objectName: "ENCRYPT_IV"
        secretPath: "bridgex/data/backend"
        secretKey: "ENCRYPT_IV"

      - objectName: "ENCRYPT_SECRET_KEY"
        secretPath: "bridgex/data/backend"
        secretKey: "ENCRYPT_SECRET_KEY"

      - objectName: "JWTSECRET"
        secretPath: "bridgex/data/backend"
        secretKey: "JWTSECRET"

      - objectName: "PRIVATEKY"
        secretPath: "bridgex/data/backend"
        secretKey: "PRIVATEKY"

      - objectName: "PUBLICKEY"
        secretPath: "bridgex/data/backend"
        secretKey: "PUBLICKEY"

      - objectName: "REDISURL"
        secretPath: "bridgex/data/backend"
        secretKey: "REDISURL"

  secretObjects:
  - secretName: backend-vault-synced-secret 
    type: Opaque
    data:
      - objectName: "ALGORITHM" 
        key: "ALGORITHM"      
      - objectName: "DBCONNECTIONSTRING" 
        key: "DBCONNECTIONSTRING"      
      - objectName: "EMAILPASS" 
        key: "EMAILPASS"      
      - objectName: "EMAILUSER" 
        key: "EMAILUSER"      
      - objectName: "ENCRYPT_IV" 
        key: "ENCRYPT_IV"      
      - objectName: "ENCRYPT_SECRET_KEY" 
        key: "ENCRYPT_SECRET_KEY"      
      - objectName: "JWTSECRET" 
        key: "JWTSECRET"      
      - objectName: "PRIVATEKY" 
        key: "PRIVATEKY"                
      - objectName: "PUBLICKEY" 
        key: "PUBLICKEY"    
      - objectName: "REDISURL" 
        key: "REDISURL"    