apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-svc
  name: backend-svc
  namespace: bridgex
spec:
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: backend-deploy
  type: ClusterIP