apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-cache-svc
  name: backend-cache-svc
  namespace: bridgex
spec:
  clusterIP: None
  ports:
  - name: 6379-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: backend-cache
  type: ClusterIP