apiVersion: v1
kind: Service
metadata:
  labels:
    app: caddy-svc
  name: caddy-svc
  namespace: bridgex
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30090
  selector:
    app: caddy
  type: NodePort