apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: bridgex
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: backend-db
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      name: main-port

    - port: 33061
      protocol: TCP
      targetPort: 33061
      name: repl-port
  
    - port: 33060
      protocol: TCP
      targetPort: 33060
      name: client-port
