apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: backend-db
    db: mysql
  name: backend-db
  namespace: bridgex
spec:
  serviceName: db-svc
  #setup volume to save data
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "freenas-nfs-csi"
      resources:
        requests:
          storage: 500M
  replicas: 1
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: backend-db
  template:
    metadata:
      labels:
        app: backend-db
    spec:
      serviceAccountName: vault-sa
      volumes:
        - name: vault-sec
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'db-secret-vault'
      #get the config and map it so mysql use it
      containers:
      - image: mysql:8.0
        imagePullPolicy: IfNotPresent
        name: mysql
        envFrom:
          - configMapRef:
              name: db-cm
          - secretRef:
              name: db-vault-synced-secret 
        ports:
        - containerPort: 3306
          protocol: TCP
        - containerPort: 33061 ##MySQL Group Replication or InnoDB Cluster setup. 
          protocol: TCP
        - containerPort: 33060
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-data
          - name: 'vault-sec'
            mountPath: '/mnt/secrets-store'
            readOnly: true
        resources: 
          requests:
            cpu: "0.2"
            memory: 500Mi