apiVersion: v1
data:
  VITE_BASE_URL: http://backend-svc.bridgex.svc.cluster.local.:8000
  VITE_WS_BASE_URL: ws://backend-svc.bridgex.svc.cluster.local.:8000
  nginx.conf: |
    server {
      listen 80;

      resolver kube-dns.kube-system.svc.cluster.local valid=10s;

      # Frontend Static Files
      location / {
          root /usr/share/nginx/html;
          index index.html;
          try_files $uri $uri/ /index.html;
      }

      # HTTP Proxy
      location /undefined/api/ {
          set $upstream_endpoint http://backend-svc.bridgex.svc.cluster.local:8000;
          rewrite ^/undefined/(.*) /$1 break;

          proxy_pass $upstream_endpoint;
          
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      # WebSocket Proxy
      location /undefined/ws/ {
          set $upstream_ws http://backend-svc.bridgex.svc.cluster.local:8000;
          rewrite ^/undefined/(.*) /$1 break;
          
          proxy_pass $upstream_ws;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
      }
    }
kind: ConfigMap
metadata:
  name: frontend-cm
  namespace: bridgex