apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gotenberg-backend-svc
  name: gotenberg-backend-svc
  namespace: bridgex
spec:
  ports:
  - name: 3001-3000
    port: 3001
    protocol: TCP
    targetPort: 3000
  selector:
    app: gotenberg-backend
  type: ClusterIP